### ISSUE TITLE
Hmmm sprawdzmy czy to działa

### ISSUE THREAD

**Issue by Amakusa22** [Piotr-Lis/FileControl#1]
https://github.com/Piotr-Lis/FileControl/blob/1f9a6025ca5998d4045dd31e5fa1026322c8dca8/control.py#L4

**Comment by Piotr-Lis** [comment]
to działa :)

**Comment by Piotr-Lis** [comment]
zamykam :)

**Comment by Piotr-Lis** [comment]
:)

**Comment by Piotr-Lis** [comment]
Issue techniczny zamykam...
