### ISSUE TITLE
Control powinien nie przyjmować lini tylko powinien korzystac z metody z klasy nadrzednej który otwiera plik i czyta go linia po lini:)

### ISSUE THREAD

**Issue by Amakusa22** [Piotr-Lis/FileControl#2]
https://github.com/Piotr-Lis/FileControl/blob/1f9a6025ca5998d4045dd31e5fa1026322c8dca8/control.py#L7

**Comment by Piotr-Lis** [comment]
tutaj właśnie miałem problem...
Chciałem uniknąć czytania pliku w każdej kontroli (może niepotrzebnie)...
dlatego też zrobiłem osobną klase do czytania pliku i zwracania samych linijek...
Wiem, że to było troszkę wbrew isntrukcji zadania...
Przebuduję to tak, żeby jednak była metoda zwracajaca linijki pliku w klasie nadrzednej Control... i bede z niej korzystać przy każdej kontroli potomnej.

**Comment by Amakusa22** [comment]
tylko że mamy tutaj sytuacje na zasadzie 
wielokrotny odczyt pliku vs przechowywanie zawartosci tego pliku w pamieci. tutaj najleży odpowiednio skorzystać z generatora który poda dane do testów. Hmm ewentualnie mozna wyciągnąc to po za klase abstrakcyjna. Natomiast najwazniejsze jest tutaj by w miare mozliwosci nie przechowwyac pliku w pamieci jezli nei musimy :)

**Comment by Piotr-Lis** [comment]
rozumiem... i poprawiam:)

**Comment by Piotr-Lis** [comment]
Poprawione.
...

**Comment by Amakusa22** [comment]
SUper! podniosłam kwestie z generatorem ale dokładnie o to mi tu chodziło :)
