### ISSUE TITLE
błedy nie powinny być w polu powinny byc tylko zwracane (ew kazde wywołanie control powinno czyscic błedy)

### ISSUE THREAD

**Issue by Amakusa22** [Piotr-Lis/FileControl#3]
https://github.com/Piotr-Lis/FileControl/blob/1f9a6025ca5998d4045dd31e5fa1026322c8dca8/controlers.py#L9

**Comment by Piotr-Lis** [comment]
Rozumiem. Poprawię...

**Comment by Piotr-Lis** [comment]
Fixed...
mozna zamykac?
