### ISSUE TITLE
extension

### ISSUE THREAD

**Issue by Amakusa22** [Piotr-Lis/FileControl#4]
https://github.com/Piotr-Lis/FileControl/blob/1f9a6025ca5998d4045dd31e5fa1026322c8dca8/file.py#L8

Ja sie ładnie prosze zapoznać, duzo ładniej jest to zrobic w ten sposob :)
|https://www.geeksforgeeks.org/how-to-get-file-extension-in-python/

**Comment by Piotr-Lis** [comment]
OK. Przeczytam i poprawie...

**Comment by Piotr-Lis** [comment]
Teraz jest duzo ładniej, thx...
Issue fixed - czy w takiej sytuacji czeka sie na akcpetacje rozwiazania od zglaszajacego problem? Czy jeśli stwierdziłem, że poprawiłem kod wg uwag to moge zamknąć wątek?

**Comment by Amakusa22** [comment]
to zależy w tej sytuacji przyjmijmy ze ja je będa zamykać :D 
normalnie raczej reviewowany sobie zamyka (review przebiega tak ze kod jest oddawany do sprawdzenia, zgłaszane sa problemy nastepnie osoba je poprawia zamyka watki i ponownie oddaje do recenzji to się kreci tak długo aż orzejdzie gładko)

jest git :)
