### ISSUE TITLE
Przywykorzystaniu generatora zmienic na next

### ISSUE THREAD

**Issue by Amakusa22** [Piotr-Lis/FileControl#6]
https://github.com/Piotr-Lis/FileControl/blob/84647908d5c5376ef316e37a6032cc294fa8eda2/controlers.py#L39

Mozna sciagnąć dana przez nexta jezeli zrobimy z tej metody generator

**Comment by Piotr-Lis** [comment]
no wlasnie tutaj nie rozumiem... napisałęm czego w tym issue z generatorem...
mam liste z liniami pliku, potrzebuje tylko pierwsza linie... indeksowanie: [0] wydawalo mi sie OK
czy generator i next() (oprocz samego przecwiczenia) cos tutaj wnosi?

**Comment by Piotr-Lis** [comment]
zrobione
