### ISSUE TITLE
enumerate pomoże :D!

### ISSUE THREAD

**Issue by Amakusa22** [Piotr-Lis/FileControl#7]
https://github.com/Piotr-Lis/FileControl/blob/84647908d5c5376ef316e37a6032cc294fa8eda2/controlers.py#L16

https://book.pythontips.com/en/latest/enumerate.html :) bardzo to tutaj pomoże

**Comment by Piotr-Lis** [comment]
ooo fajne... nie znałem.
Pomogło.
commit jak dokoncze...
