### ISSUE TITLE
comprehensione spróbujemy :D!

### ISSUE THREAD

**Issue by Amakusa22** [Piotr-Lis/FileControl#8]
https://github.com/Piotr-Lis/FileControl/blob/84647908d5c5376ef316e37a6032cc294fa8eda2/controlers.py#L21

tu jest potencjał na comprehension przynajmniej ten mały for :)

**Comment by Piotr-Lis** [comment]
zrobione...
kusi zeby zrobic comprehensions w comprehensions ale to bedzie chyba 'too much'... :)
Commit jak bedzie reszta gotowa

**Comment by Piotr-Lis** [comment]
done
